apiVersion: "v1"
kind: "Secret"
type: "Opaque"
metadata: 
  name: "pgprimary-secret"
data: 
  PG_USER: {{ default "" .Values.config.PG_USER | b64enc | quote }}
  PG_DATABASE: {{ default "" .Values.config.PG_DATABASE | b64enc | quote }}
  PG_PASSWORD: {{ default "" .Values.config.PG_PASSWORD | b64enc | quote }}
  PG_PRIMARY_USER: {{ default "" .Values.config.PG_PRIMARY_USER | b64enc | quote }}
  PG_PRIMARY_PASSWORD: {{ default "" .Values.config.PG_PRIMARY_PASSWORD | b64enc | quote }}
  PG_ROOT_PASSWORD: {{ default "" .Values.config.PG_ROOT_PASSWORD | b64enc | quote }}