# Default values for thumbor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

thumbor:
  image:
    repository: registry.cn-shenzhen.aliyuncs.com/thinker-open/thumbor
    tag: 6.6.0
    pullPolicy: IfNotPresent
  resources: 
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 128Mi

nginx:
  image:
    repository: registry.cn-shenzhen.aliyuncs.com/thinker-open/thumbor-nginx
    tag: 1.0.1
    pullPolicy: IfNotPresent
  resources: 
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

nodeSelector: {}

thumborConfig: 
  THUMBOR_PORT: 8000
  ALLOW_UNSAFE_URL: "True"
  LOG_LEVEL: "INFO"
  DETECTORS: "['thumbor.detectors.feature_detector','thumbor.detectors.face_detector']"
  AWS_ACCESS_KEY_ID: test
  AWS_SECRET_ACCESS_KEY: test
  # aws:eu-central-1 minio:us-east-1
  TC_AWS_REGION: us-east-1  
  TC_AWS_ENDPOINT: https://minio.domain.vc
  TC_AWS_ENABLE_HTTP_LOADER: "False"
  LOADER: "tc_aws.loaders.s3_loader"
  TC_AWS_LOADER_BUCKET: images
  TC_AWS_LOADER_ROOT_PATH: 
  STORAGE: "tc_aws.storages.s3_storage"
  TC_AWS_STORAGE_BUCKET: thumbor-storage
  TC_AWS_STORAGE_ROOT_PATH: storage
  RESULT_STORAGE: "tc_aws.result_storages.s3_storage"
  TC_AWS_RESULT_STORAGE_BUCKET: thumbor-storage
  TC_AWS_RESULT_STORAGE_ROOT_PATH: result_storage
  RESULT_STORAGE_STORES_UNSAFE: "True"
  STORAGE_EXPIRATION_SECONDS: None
  RESULT_STORAGE_EXPIRATION_SECONDS: None