apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.es.name }}
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: {{ .Values.es.name }}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Elasticsearch"
    chart: {{ template "efk.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: db
  selector:
    k8s-app: {{ .Values.es.name }}
