apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.kibana.ingress.basicAuth.authSecret }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
{{ (.Files.Glob "kibana-secrets/*").AsSecrets | indent 2 }}